n1 = float(input("ENTER A VALUE IN KILOMETER TO CONVERT INTO MILES"))
print("IN MILES: ",n1*0.62137119)
n2 = float(input("ENTER A VALUE IN CELCIUS TO CONVERT INTO FAHRENHEIT"))
print("IN FAHRENHIET: ",(n2*1.8)+32)
